syntax on
filetype plugin on
filetype indent on

set number
set relativenumber
set hlsearch
set wrap
set wildmode=longest:list
set incsearch

set laststatus=2
set statusline=
set statusline+=%1*\%F         " Filename
set statusline+=%1*\ %=\ %l/%L " Row/Total row
set statusline+=%1*\ %3v\      " Virtual column

let g:matchparen_timeout=10
let g:matchparen_insert_timeout=10

" Highlight trailing whitespace
highlight Whitespace ctermbg=red
match Whitespace /\s\+$/
autocmd BufWinEnter * match Whitespace /\s\+$/
autocmd InsertEnter * match Whitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match Whitespace /\s\+$/

xnoremap "+y y:call system("wl-copy", @")<cr>
nnoremap "+p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
nnoremap "*p :let @"=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>p

nmap <silent><nowait> gd <Plug>(coc-definition)
" nmap <silent><nowait> gi <Plug>(coc-implementation)
" nmap <silent><nowait> gy <Plug>(coc-type-definition)
