#!/bin/bash

if [[ -f ~/.bashrc ]] ; then
	. ~/.bashrc
fi

# start tmux if this is an ssh connection
if [[ -n "$SSH_CONNECTION" ]] && [[ -z "$TMUX" ]] && which tmux > /dev/null 2>&1; then
	exec tmux new-session -A -s ssh
fi

if [[ -z "$SSH_CONNECTION" ]] && which Hyprland > /dev/null 2>&1 && [[ "$(id -u)" -ne 0 ]]; then
	exec dbus-run-session Hyprland
fi
