set -o vi

export EDITOR='vim'
export VISUAL=$EDITOR
export PATH="$PATH:$HOME/.local/bin"

alias ls='ls --color=always'
alias grep='grep --color=always'
alias dmesg='dmesg --color=always'
alias eix='eix --color=always -c'
alias diff='diff --color=always'

PS1='\[\033[0;31m\]\h \[\033[0;34m\]\W $(if [[ $? != 0 ]]; then echo -e "\[\[\033[0;31m\]"; fi)\$ \[\033[0m\]'
