#!/bin/bash

if [[ -f ~/.bashrc ]] ; then
	. ~/.bashrc
fi

# start tmux if this is an ssh connection
if [[ -n "$SSH_CONNECTION" ]] && [[ -z "$TMUX" ]] && command -v tmux > /dev/null 2>&1 ; then
	tmux new-session -A -s ssh
fi

if which Hyprland > /dev/null 2>&1 && [[ "$(id -u)" -ne 0 ]]; then
	exec dbus-run-session Hyprland
fi
