export EDITOR='vim'
export VISUAL=$EDITOR
export PATH="$PATH:$HOME/.local/bin"

PS1='\[\033[0;31m\]\h \[\033[0;34m\]\W $(if [[ $? != 0 ]]; then echo -e "\[\[\033[0;31m\]"; fi)\$ \[\033[0m\]'

alias ls="ls --color=always"
alias grep="grep --color=always -I"
alias less="less -R"

PROMPT_COMMAND='history -a'

if which fzf > /dev/null 2>&1; then
	source <(fzf --bash)
fi
